# Atari 800 Software Sources

base_path: Atari/800/Software

sources:
  - name: TOSEC Atari 8-bit Collection
    type: ddl
    url: https://archive.org/download/Atari_8bit_TOSEC_2012_04_23/Atari_8bit_TOSEC_2012_04_23.zip
    folder: ROMs

#https://ia601908.us.archive.org/view_archive.php?archive=/10/items/atari-800/Atari800.rar
#https://archive.org/download/Atari800RomCollectionByGhostware

# System Roms
# http://atari.vjetnam.cz/dow/emuROMs.zip

