cache:
  dir_cache_enabled: true
  dir_listing_cache_enabled: true
  getattr_cache_enabled: true
  getattr_cache_save_interval: 5.0
  readdir_direntry_cache_enabled: true
  readdir_skip_cache_lookup_with_direntry: true
  transform_output_size_cache_enabled: true
  transform_pipeline_cache_enabled: true
cache_warmer:
  batch_size: 10
  check_interval_seconds: 5
  cpu_threshold_percent: 20.0
  enabled: false
  io_threshold_percent: 20.0
  max_depth: 12
database:
  auto_sync: false
  enabled: true
  mode: hybrid
  path: /mnt/filestorefs/.transfs_metadata.db
  sync_on_startup: false
filestore: /mnt/filestorefs
mountpoint: /mnt/transfs
ssl_ignore_hosts:
- arcarc.nl
ui:
  advanced_options: true
web_api:
  host: ''
  port: 8000
zaparoo:
  clients:
  - enabled: true
    host: 192.168.95.78
    mount_path: /media/fat/cifs
    name: MiSTer
    port: 7497
