# Acorn Archimedes Software Sources

base_path: 3DO/3DO/

sources:
  - name: bios
    type: ddl
    urls: 
     - https://github.com/trapexit/3do-bios/blob/master/3do_arcade_saot.bin
     - https://github.com/trapexit/3do-bios/blob/master/goldstar.bin
     - https://github.com/trapexit/3do-bios/blob/master/panafz1-kanji.bin
     - https://github.com/trapexit/3do-bios/blob/master/panafz1.bin
     - https://github.com/trapexit/3do-bios/blob/master/panafz10-patched.bin
     - https://github.com/trapexit/3do-bios/blob/master/panafz10.bin
     - https://github.com/trapexit/3do-bios/blob/master/panafz10e-anvil-patched.bin
     - https://github.com/trapexit/3do-bios/blob/master/panafz10e-anvil.bin
     - https://github.com/trapexit/3do-bios/blob/master/panafz10ja-anvil-kanji.bin
     - https://github.com/trapexit/3do-bios/blob/master/sanyotry.bin
    folder: BIOS
    metadata:
      ruleset: Generic
      defaults:
        media_type: BIOS
        region: World
        language: English

  - name: 3do-top-10
    type: ddl
    urls:
    - https://archive.org/download/rr-3do/usa/Crash%20%27n%20Burn%20%281993%29%20%28Crystal%20Dynamics%29%20%28US%29%20%5B%21%5D.7z
    folder: Software/Collections/3DO_Top_10
    extract: true
    metadata:
      ruleset: Generic
      defaults:
        media_type: CD
        region: World
        language: English
    
  - name: 3do-interactive-samplers
    type: ddl
    urls: 
    - https://archive.org/download/the-3do-interactive-sampler-cd-4-3do-usa/The_3DO_Interactive_Sampler_CD_4.bin
    - https://archive.org/download/the-3do-interactive-sampler-cd-4-3do-usa/The_3DO_Interactive_Sampler_CD_4.cue
    folder: Software/Collections/3DO_Interactive_Sampler
    extract: false
    metadata:
      ruleset: Generic
      defaults:
        media_type: CD
        region: World
        language: English
  

packs:
  - id: just-bio
    name: Bioses Only
    description: Essential BIOS files no software
    estimated_size: 710MB
    sources: [bios,3do-interactive-samplers]
    supported_by: [RetroBat,Batocera,RetroPie,MiSTer]
    info_links:
      - label: IA Page
        url: "https://ia803104.us.archive.org/view_archive.php?archive=/8/items/MAME217RomsOnlyMerged/MAME%200.217%20ROMs%20%28merged%29.zip"

  - id: minimal
    name: Minimal Starter Set
    description: Essential BIOS files and a samplers, to test the system
    estimated_size: 710MB
    sources: [bios,3do-interactive-samplers]
    supported_by: [RetroBat,Batocera,RetroPie,MiSTer]
  
