# Apple II Software Sources

base_path: Apple/AppleII/

sources:
  - name: Unknown-IA
    type: ddl
    url: https://archive.org/download/Apple_II_201808/ROMs.zip
    folder: Software/2mg
    extract: true

sources:
  - name: apple2.org.za-prodos
    type: ddl
    urls:
     - https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/masters/prodos/Apple%27s%20ProDOS%20System%20Utilities%20-%20Filer%20v1.1.dsk
     - https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/masters/prodos/Apple%20IIe%20ProDOS%20Users%20Disk%20%28copied%203-12-85%29.dsk
     - https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/masters/prodos/APPLE%20II%20SYSTEM%20UTILITIES%202.1.dsk
     -
    folder: Software/dsk

sources:
  - name: apple2-top20games
    type: ddl
    urls:
     - https://apple2online.com/wp-content/uploads/Ultima-I.zip
     - https://apple2online.com/wp-content/uploads/Wolfenstein-3D-GS.zip
     - https://apple2online.com/wp-content/uploads/Wizardry-I.zip
     - https://apple2online.com/wp-content/uploads/Swashbuckler.zip
     - https://apple2online.com/wp-content/uploads/Choplifter-A2OL.zip
     - https://apple2online.com/wp-content/uploads/lode_runner.zip
     - https://apple2online.com/wp-content/uploads/cavern_creatures.zip
     - https://apple2online.com/wp-content/uploads/Kings-Quest-I-GS.zip
     - https://apple2online.com/wp-content/uploads/Karateka.zip
     - https://apple2online.com/wp-content/uploads/Impossible-Mission-A2OL.zip
     - https://apple2online.com/wp-content/uploads/The-Bards-Tale.zip
     - https://www.virtualapple.org/apple2/OT(Disk1of2).zip
     - https://www.virtualapple.org/apple2/OT(Disk2of2).zip
     - https://apple2online.com/wp-content/uploads/Elite.zip
     - https://apple2online.com/wp-content/uploads/Might-and-Magic-1.zip
     - https://www.virtualapple.org/apple2/Pirates!(cracked)(Boot)(Disk1of4).zip
     - https://www.virtualapple.org/apple2/Pirates!(cracked)(Boot)(Disk2of4).zip
     - https://www.virtualapple.org/apple2/Pirates!(cracked)(Boot)(Disk3of4).zip
     - https://www.virtualapple.org/apple2/Pirates!(cracked)(Boot)(Disk4of4).zip
     - https://apple2online.com/wp-content/uploads/California-Games.zip
     - https://apple2online.com/wp-content/uploads/maniac_mansion.zip
     - https://apple2online.com/wp-content/uploads/Wasteland.zip
     - https://apple2online.com/wp-content/uploads/Prince-of-Persia.zip
     - https://apple2online.com/wp-content/uploads/Battle-Chess-GS.zip

    folder: Software/dsk
    extract: true

packs:

  - id: appple2top20games
    name: Top 20 Apple II Games
    description: A collection of the top 20 Apple II games from apple2online.com and virtualapple.org
    estimated_size: 2MB
    sources: [apple2-top20games]
    supported_by: [MiSTer]
    info_links:
      - label: Apple2Online
        url: https://apple2online.com/

      - label: Virtual Apple
        url: https://www.virtualapple.org/

      - label: 20 Games That Defined the Apple II (Youtube)
        url: https://www.youtube.com/watch?v=dk5p7RjmlpQ

  - id: appple2orgza-prodos
    name: Prodos
    description: A collection of ProDOS system disks from apple2.org.za
    estimated_size: 2MB
    sources: [apple2.org.za-prodos]
    supported_by: [MiSTer]
    info_links:
      - label: apple2.org.za mirrors archive
        url: https://mirrors.apple2.org.za/


  - id: IA-Apple2
    name: Unknown IA collection of disks
    description: A great selection of mainy games for the AppleII
    estimated_size: 166MB
    sources: [Unknown-IA]
    supported_by: [MiSTer]
    info_links:
      - label: IA page
        url: https://archive.org/details/Apple_II_201808
