# Acorn Atom Software Sources

# Base path must match clients.yaml local_base_path (no Software/ suffix)
base_path: Acorn/Atom/

sources:

  - name: MameBIOSroms
    type: ddl
    urls:
      - "https://ia803104.us.archive.org/view_archive.php?archive=/8/items/MAME217RomsOnlyMerged/MAME%200.217%20ROMs%20%28merged%29.zip&file=atom.zip"
    folder: Software/BIOS
    extract: false

  - name: hoglet67
    type: ddl
    urls:
      - https://github.com/hoglet67/AtomSoftwareArchive/releases/download/V13_00/AtomSoftwareArchive_20240505_1129_V13.00.zip
    folder: Software/Collections/hoglet67/main
    extract: true
  
  - name: blankvhd
    type: ddl
    urls:
      - https://github.com/MiSTer-devel/AcornAtom_MiSTer/raw/main/releases/blank.zip
    folder: Software/Utils
    extract: true

packs:

  - id: mame_atom_bios
    name: BIOS ROMs for MAME/MESS derivatives
    description: BIOS ROMs for MAME/MESS derivatives
    estimated_size: 32k
    sources: [MameBIOSroms]
    supported_by: [RetroBat,Mame,Batocera,RetroPie]
    info_links:
      - label: IA Page
        url: "https://ia803104.us.archive.org/view_archive.php?archive=/8/items/MAME217RomsOnlyMerged/MAME%200.217%20ROMs%20%28merged%29.zip"
    metadata:
      ruleset: Generic
      defaults:
        media_type: Tape
        region: World
        language: English

  - id: hoglet67
    name: hoglet67s Atom Software Collection
    description: hoglet67s Atom Software Collection (both as files and built into a VHD)
    estimated_size: 15.3MB
    sources: [hoglet67, blankvhd]
    build_script: MiSTer/Acorn/Atom/build.sh
    info_links:
      - label: Hoglet67s Atom Software Archive
        url: https://github.com/hoglet67/AtomSoftwareArchive
    supported_by: [MiSTer,RetroBat,Mame,Batocera,RetroPie]
    metadata:
      ruleset: Generic
      defaults:
        media_type: Disk
        region: World
        language: English
        extension: ATM

